######################################################################
#
# File name : LoadBoard_tb_compile.do
# Created on: Fri Jun 15 22:39:37 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../Mips54_LoadBoard_vMDU.srcs/sources_1/imports/54cpu_up" "+incdir+../../../../Mips54_LoadBoard_vMDU.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"LoadBoard_tb_func_synth.v" \
"../../../../Mips54_LoadBoard_vMDU.srcs/sim_1/imports/new/LoadBoard_tb.v" \


quit -force

