######################################################################
#
# File name : LoadBoard_tb_wave.do
# Created on: Fri Jun 15 22:39:42 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
