######################################################################
#
# File name : LoadBoard_tb.udo
# Created on: Fri Jun 15 02:02:24 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
