######################################################################
#
# File name : LoadBoard_tb_compile.do
# Created on: Sun Jun 17 02:53:42 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xpm
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/dist_mem_gen_v8_0_10

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib
C:\\modeltech_pe_10.4c\\win32pe\\vmap xpm msim/xpm
C:\\modeltech_pe_10.4c\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code" "+incdir+../../../Mips54_LoadBoard_vMDU.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"D:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
"D:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
"D:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
"D:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
"D:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
"D:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
"D:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \

C:\\modeltech_pe_10.4c\\win32pe\\vcom -64 -93 -work xpm  \
"D:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd" \

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code" "+incdir+../../../Mips54_LoadBoard_vMDU.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/vga_sync.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/DIVU.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/DIV.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/mult.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/multu.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/ip/gmem/gmem_sim_netlist.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/vga_controller.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/pcreg.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/ControlUnit.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/ALU.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/regfile.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/MDU.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/cp0.v" \

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  "+incdir+../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code" "+incdir+../../../Mips54_LoadBoard_vMDU.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../Mips54_LoadBoard_vMDU.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code" "+incdir+../../../Mips54_LoadBoard_vMDU.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/ip/imem/sim/imem.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/ip/dmem/sim/dmem.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_sim_netlist.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/vga.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/IO_Interface.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/cpu.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sources_1/verilog_code/MipsSuperRacing.v" \
"../../../Mips54_LoadBoard_vMDU.srcs/sim_1/imports/new/LoadBoard_tb.v" \

# compile glbl module
C:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

