######################################################################
#
# File name : LoadBoard_tb_wave.do
# Created on: Sun Jun 17 02:53:50 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
