# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/WeCloudSync/6.MI_PROJECTS/VIVADO_PROJECT/Mips54_App/Mips54_App/Mips54_LoadBoard_vMDU.srcs/sources_1/ip/gmem/gmem.xci
# IP: The module: 'gmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WeCloudSync/6.MI_PROJECTS/VIVADO_PROJECT/Mips54_App/Mips54_App/Mips54_LoadBoard_vMDU.srcs/sources_1/ip/gmem/gmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gmem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/WeCloudSync/6.MI_PROJECTS/VIVADO_PROJECT/Mips54_App/Mips54_App/Mips54_LoadBoard_vMDU.srcs/sources_1/ip/gmem/gmem.xci
# IP: The module: 'gmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WeCloudSync/6.MI_PROJECTS/VIVADO_PROJECT/Mips54_App/Mips54_App/Mips54_LoadBoard_vMDU.srcs/sources_1/ip/gmem/gmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
